### ISSUE TITLE
Possibility to specify loadBalancerClass for the exposed services

### ISSUE THREAD

**Issue by zentavr** [percona/percona-postgresql-operator#877]
### Proposal

It would be great to be able to specify '/spec/loadBalancerClass' value when setting up a service exposure.
We have several load balancer and MetallB catch only the configuration which is specified with that field.

### Is this a feature you are interested in implementing yourself?

No

### Anything else?

no

**Comment by zentavr** [comment]
As a workaround you can [install kubemod operator](https://github.com/kubemod/kubemod/tree/v0.20.0?tab=readme-ov-file#installation) inside your cluster and patch the service on the fly, like:
```yaml
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: zabbix-database-pgbouncer-svc-mod
  namespace: zabbix
spec:
  type: Patch

  match:
    # Match Services ...
    - select: '$.kind'
      matchValue: Service
    - select: '$.metadata.name'
      matchValue: zabbix-database-pgbouncer

    # ... created by the percona operator.
    - select: '$.metadata.labels["app.kubernetes.io/component"]'
      matchValue: pgbouncer
    - select: '$.metadata.labels["app.kubernetes.io/instance"]'
      matchValue: zabbix-database
    - select: '$.metadata.labels["app.kubernetes.io/managed-by"]'
      matchValue: percona-postgresql-operator

  patch:
    # Add custom annotation.
    - op: add
      path: /spec/loadBalancerClass
      value: metallb
```
