### ISSUE TITLE
When creating new `PerconaPGCluster` pgbouncer is always deployed, even if not specified

### ISSUE THREAD

**Issue by Kajot-dev** [percona/percona-postgresql-operator#935]
### Report

When deploying new `PerconaPGCluster` without the `proxy` section altogether, underlying `PostgresCluster` has pgbouncer defined with exactly one replica - but it should be not deployed at all. 

Behavior is correct when using `PostgresCluster` directly or when migrating from an existing `PostgresCluster` to `PerconaPGCluster` (pgbouncer is not deployed)

### More about the problem

Pgbouncer is deployed with one replica, even though pgbouncer configuration was not specified at all

### Steps to reproduce

1.  Create new `PerconaPGCLuster`
For example:
```yaml
metadata:
  name: test-pg
  namespace: test-ns
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
      name: test
      replicas: 2
  port: 5432
  postgresVersion: 16
```
3. Observe pgbouncer being deployed 
4. Create **exact same** (but with a different name) cluster using `PostgresCluster` CR directly and you'll see no pbbouncer deployed

### Versions

1. Kubernetes 1.28
2. Operator 2.5.0
3. Database 16.4
